

pipeline {
  agent any
  tools {nodejs "node"}

  stages {
    
    stage('checkout') {
      steps {
        git 'https://github.com/nagabhushanamn/example-apps'
      }
    }

    stage('unit tests') {
      steps {
        dir('node-app') {
         sh 'npm i'
         sh 'npm test'
        }
      }
    }
    
  }
}