

pipeline {
  agent any
  tools {nodejs "node"}

  stages {
    
    stage('Checkout') {
      steps {
        git 'https://github.com/nagabhushanamn/example-apps'
      }
    }

    stage('Test') {
      steps {
        dir('node-app') {
         sh 'npm i'
         sh 'npm test'
        }
      }
      post {
        always {
          step([$class: 'CoberturaPublisher', coberturaReportFile: 'output/coverage/jest/cobertura-coverage.xml'])
        }
      }
    }

  }
}